spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT  1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true
  profiles:
    active: house