server:
  port: 9090
spring:
  datasource:
    tomcat:
      test-on-borrow: true
      validation-query: SELECT  1
  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        多数据源不生效
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    # 显式设置为true，最后框架会选择update方式
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true
        ddl-auto: update
#       implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        # column 下划线
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  profiles:
    active: dev,house,system
# 日志配置
logging:
  config: classpath:log/logback-config.xml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.gyw.backend
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
  setting:
    language: zh_cn

#######################################
# 自定义配置
cn:
  gyw:
    log:
      path: /Users/guanyw/Temp/logs
    security:
      enable: true
      urls:
        un-auth-urls:
          - /v3/api-docs/**
